---
version: '3.1'
services:
  my-sql-db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: risk_engine
      MYSQL_USER: re_user
      MYSQL_PASSWORD: letmein
    ports:
      - '3306:3306'
    volumes:
      - my-sql-db:/var/lib/mysql-db

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'

  kafka-broker:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka-broker
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'payments:1:1,validated-payments:1:1'
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: INFO
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  risk-engine:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        APP_SERVICE_NAME: risk-engine
    environment:
      DB_HOST: my-sql-db
      DB_PORT: 3306
      KAFKA_BOOTSTRAP_SERVER_HOST: kafka-broker
      KAFKA_BOOTSTRAP_SERVER_PORT: 9092
    depends_on:
      - my-sql-db
      - kafka-broker

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        APP_SERVICE_NAME: payment-service
    environment:
      KAFKA_BOOTSTRAP_SERVER_HOST: kafka-broker
      KAFKA_BOOTSTRAP_SERVER_PORT: 9092
    ports:
      - '8080:8080'
    depends_on:
      - kafka-broker

volumes:
  my-sql-db:

