---
version: '3.1'
services:
  my-sql-db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    hostname: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - my-sql-db:/var/lib/mysql-db

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: ${ZOOKEEPER_HOST}
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
    ports:
      - '${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}'

  kafka-broker:
    image: wurstmeister/kafka
    hostname: ${BROKER_HOST}
    ports:
      - '${BROKER_PORT}:${BROKER_PORT}'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${BROKER_HOST}
      KAFKA_ADVERTISED_PORT: ${BROKER_PORT}
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOST}:${ZOOKEEPER_PORT}
      KAFKA_CREATE_TOPICS: '${PAYMENTS_TOPIC}:1:1,${PAYMENT_VALIDATIONS_TOPIC}:1:1'
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: INFO
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  risk-engine:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        APP_SERVICE_NAME: ${RISK_ENGINE_SERVICE_NAME}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      KAFKA_BOOTSTRAP_SERVER_HOST: ${BROKER_HOST}
      KAFKA_BOOTSTRAP_SERVER_PORT: ${BROKER_PORT}
      PAYMENTS_TOPIC: ${PAYMENTS_TOPIC}
      PAYMENT_VALIDATIONS_TOPIC: ${PAYMENT_VALIDATIONS_TOPIC}
    depends_on:
      - my-sql-db
      - kafka-broker

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        APP_SERVICE_NAME: ${PAYMENTS_SERVICE_NAME}
    environment:
      PAYMENT_SERVICE_HOST: ${PAYMENTS_SERVICE_NAME}
      PAYMENT_SERVICE_PORT: ${PAYMENTS_SERVICE_PORT}
      KAFKA_BOOTSTRAP_SERVER_HOST: ${BROKER_HOST}
      KAFKA_BOOTSTRAP_SERVER_PORT: ${BROKER_PORT}
      PAYMENTS_TOPIC: ${PAYMENTS_TOPIC}
      PAYMENT_VALIDATIONS_TOPIC: ${PAYMENT_VALIDATIONS_TOPIC}
    ports:
      - '${PAYMENTS_SERVICE_PORT}:${PAYMENTS_SERVICE_PORT}'
    depends_on:
      - kafka-broker

volumes:
  my-sql-db:

